- name: Install and run nginx
  hosts: mongodb
  become: yes #this will give root access
  tasks: 
  - name: Install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
