- name: variables in ansible 
  hosts: mongodb
  become: yes
  vars:
    COURSE: devops
    TRAINER: Vignan
    DURATION: 110HRS
  tasks: 
  - name: print hello world
    ansible.builtin.debug:
      msg: "hello world! I am practicing the devops!"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello I am learning {{COURSE}}!, duration is {{DURATION}}, {{TRAINER}} is the trainer!"


