- name: create dynamic user
  hosts: localhost
  vars_prompt:
  - name: USER
    prompt: please enter the user
    private: false 
  tasks:
  - name: check if the user exists or not
    ansible.builtin.command: id {{USER}}
    register: output
    ignore_errors: true
  - name: print the output
    ansible.builtin.debug:
      msg: "output is {{output}}" 
  - name: print the exit status
    ansible.builtin.debug:
      msg: "exit status is {{output.rc}}"
    
  
